name: Transfer Docker Image to Docker Hub

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository address'
        required: true
      tag:
        description: 'Target tag'
        default: 'latest'

jobs:
  transfer_image:
    runs-on: ubuntu-latest
    
    steps:
    - name: Parse Docker Image Name
      id: parse_image_name
      run: |
        image_name=$(echo "${{ github.event.inputs.repository }}" | sed 's/[\/.]/-/g; s/:.*$//')
        echo "parsed_image_name=$image_name" >> $GITHUB_OUTPUT
      shell: bash

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Pull from Input Image
      run: docker pull ${{ github.event.inputs.repository }}

    - name: Tag Docker Image
      run: docker tag ${{ github.event.inputs.repository }} ${{ secrets.DOCKER_HUB_USER }}/${{ steps.parse_image_name.outputs.parsed_image_name }}:${{ github.event.inputs.tag }}

    - name: Push to Docker Hub
      run: docker push ${{ secrets.DOCKER_HUB_USER }}/${{ steps.parse_image_name.outputs.parsed_image_name }}:${{ github.event.inputs.tag }}
